version: '2'

volumes:
  database_data:
    driver: local

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: api_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
